/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const BhajanEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioBase64' : IDL.Text,
  'createdAt' : Time,
  'lyricsText' : IDL.Text,
  'artist' : IDL.Text,
  'deity' : IDL.Text,
});
export const HolyBookEntry = IDL.Record({
  'id' : IDL.Text,
  'bookTitle' : IDL.Text,
  'shlokaText' : IDL.Text,
  'bookCategory' : IDL.Text,
  'audioBase64' : IDL.Text,
  'trackNumber' : IDL.Nat,
  'createdAt' : Time,
  'chapterTitle' : IDL.Text,
});
export const PrasadDeliveryRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'mobileNumber' : IDL.Text,
  'address' : IDL.Text,
  'templeId' : IDL.Text,
});
export const VratKathaEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioBase64' : IDL.Text,
  'storyText' : IDL.Text,
  'createdAt' : Time,
  'festivalName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AstrologerProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'languages' : IDL.Vec(IDL.Text),
  'experienceYears' : IDL.Nat,
  'perMinuteRate' : IDL.Float64,
  'rating' : IDL.Float64,
  'specializations' : IDL.Vec(IDL.Text),
});
export const BusinessNameRecord = IDL.Record({
  'id' : IDL.Text,
  'result' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'businessName' : IDL.Text,
});
export const ChadhavaOffering = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'templeId' : IDL.Text,
  'items' : IDL.Vec(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ConsultationAppointment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'topic' : IDL.Text,
  'astrologerId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Text,
  'specialQuestions' : IDL.Text,
});
export const DevotionalContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'contentType' : IDL.Text,
  'createdAt' : Time,
  'language' : IDL.Text,
  'deity' : IDL.Text,
});
export const NumerologyRecord = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'result' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Float64,
  'paymentStatus' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'stripePaymentIntentId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'astrologicalPurpose' : IDL.Text,
  'category' : IDL.Text,
  'benefits' : IDL.Text,
  'price' : IDL.Float64,
});
export const PujaBooking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'pujaType' : IDL.Text,
  'specialWishes' : IDL.Text,
  'gotra' : IDL.Text,
  'preferredDate' : IDL.Text,
  'templeId' : IDL.Text,
  'devoteeName' : IDL.Text,
});
export const ReportRequest = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'pob' : IDL.Text,
  'tob' : IDL.Text,
  'status' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'reportType' : IDL.Text,
});
export const Temple = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'deity' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'birthDate' : IDL.Text,
  'birthTime' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'birthPlace' : IDL.Text,
  'email' : IDL.Text,
  'gotra' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VirtualTempleConfig = IDL.Record({
  'background' : IDL.Text,
  'decorStyle' : IDL.Text,
  'userId' : IDL.Principal,
  'updatedAt' : Time,
  'items' : IDL.Vec(IDL.Text),
  'deity' : IDL.Text,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBhajan' : IDL.Func([BhajanEntry], [], []),
  'addHolyBookEntry' : IDL.Func([HolyBookEntry], [], []),
  'addUserPrasadDeliveryRequest' : IDL.Func([PrasadDeliveryRequest], [], []),
  'addVratKatha' : IDL.Func([VratKathaEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAstrologerProfile' : IDL.Func([AstrologerProfile], [], []),
  'createBusinessNameRecord' : IDL.Func([BusinessNameRecord], [], []),
  'createChadhavaOffering' : IDL.Func([ChadhavaOffering], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createConsultationAppointment' : IDL.Func([ConsultationAppointment], [], []),
  'createDevotionalContent' : IDL.Func([DevotionalContent], [], []),
  'createNumerologyRecord' : IDL.Func([NumerologyRecord], [], []),
  'createOrder' : IDL.Func([Order], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'createPujaBooking' : IDL.Func([PujaBooking], [], []),
  'createReportRequest' : IDL.Func([ReportRequest], [], []),
  'createTemple' : IDL.Func([Temple], [], []),
  'deleteBhajan' : IDL.Func([IDL.Text], [], []),
  'deleteDevotionalContent' : IDL.Func([IDL.Text], [], []),
  'deleteHolyBookEntry' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteVratKatha' : IDL.Func([IDL.Text], [], []),
  'getAllAstrologerProfiles' : IDL.Func(
      [],
      [IDL.Vec(AstrologerProfile)],
      ['query'],
    ),
  'getAllConsultationAppointments' : IDL.Func(
      [],
      [IDL.Vec(ConsultationAppointment)],
      ['query'],
    ),
  'getAllDeliveryRequests' : IDL.Func(
      [],
      [
        IDL.Vec(IDL.Tuple(IDL.Text, PrasadDeliveryRequest)),
        IDL.Vec(IDL.Tuple(IDL.Text, PujaBooking)),
      ],
      ['query'],
    ),
  'getAllDevotionalContents' : IDL.Func(
      [],
      [IDL.Vec(DevotionalContent)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllTemples' : IDL.Func([], [IDL.Vec(Temple)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAstrologerProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AstrologerProfile)],
      ['query'],
    ),
  'getBhajanById' : IDL.Func([IDL.Text], [IDL.Opt(BhajanEntry)], ['query']),
  'getBhajans' : IDL.Func([], [IDL.Vec(BhajanEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevotionalContent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DevotionalContent)],
      ['query'],
    ),
  'getHolyBookEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HolyBookEntry)],
      ['query'],
    ),
  'getHolyBookEntryById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HolyBookEntry)],
      ['query'],
    ),
  'getPendingPrasadDeliveries' : IDL.Func(
      [],
      [IDL.Vec(PrasadDeliveryRequest)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserBusinessNameRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BusinessNameRecord)],
      ['query'],
    ),
  'getUserChadhavaOfferings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChadhavaOffering)],
      ['query'],
    ),
  'getUserConsultationAppointments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ConsultationAppointment)],
      ['query'],
    ),
  'getUserNumerologyRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(NumerologyRecord)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserPrasadDeliveryRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PrasadDeliveryRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserPujaBookings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PujaBooking)],
      ['query'],
    ),
  'getUserReportRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReportRequest)],
      ['query'],
    ),
  'getVirtualTempleConfig' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VirtualTempleConfig)],
      ['query'],
    ),
  'getVratKathaById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VratKathaEntry)],
      ['query'],
    ),
  'getVratKathas' : IDL.Func([], [IDL.Vec(VratKathaEntry)], ['query']),
  'getWalletBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getWalletTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'handlePujaBooking' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'rechargeWallet' : IDL.Func(
      [IDL.Principal, IDL.Float64, WalletTransaction],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVirtualTempleConfig' : IDL.Func([VirtualTempleConfig], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBhajan' : IDL.Func([BhajanEntry], [], []),
  'updateConsultationAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateDevotionalContent' : IDL.Func([DevotionalContent], [], []),
  'updateHolyBookEntry' : IDL.Func([HolyBookEntry], [], []),
  'updateOrderPaymentStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePrasadDeliveryStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateReportRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateVratKatha' : IDL.Func([VratKathaEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const BhajanEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioBase64' : IDL.Text,
    'createdAt' : Time,
    'lyricsText' : IDL.Text,
    'artist' : IDL.Text,
    'deity' : IDL.Text,
  });
  const HolyBookEntry = IDL.Record({
    'id' : IDL.Text,
    'bookTitle' : IDL.Text,
    'shlokaText' : IDL.Text,
    'bookCategory' : IDL.Text,
    'audioBase64' : IDL.Text,
    'trackNumber' : IDL.Nat,
    'createdAt' : Time,
    'chapterTitle' : IDL.Text,
  });
  const PrasadDeliveryRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'mobileNumber' : IDL.Text,
    'address' : IDL.Text,
    'templeId' : IDL.Text,
  });
  const VratKathaEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioBase64' : IDL.Text,
    'storyText' : IDL.Text,
    'createdAt' : Time,
    'festivalName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AstrologerProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'languages' : IDL.Vec(IDL.Text),
    'experienceYears' : IDL.Nat,
    'perMinuteRate' : IDL.Float64,
    'rating' : IDL.Float64,
    'specializations' : IDL.Vec(IDL.Text),
  });
  const BusinessNameRecord = IDL.Record({
    'id' : IDL.Text,
    'result' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'businessName' : IDL.Text,
  });
  const ChadhavaOffering = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'templeId' : IDL.Text,
    'items' : IDL.Vec(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ConsultationAppointment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'topic' : IDL.Text,
    'astrologerId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Text,
    'specialQuestions' : IDL.Text,
  });
  const DevotionalContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'contentType' : IDL.Text,
    'createdAt' : Time,
    'language' : IDL.Text,
    'deity' : IDL.Text,
  });
  const NumerologyRecord = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'result' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Float64,
    'paymentStatus' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'stripePaymentIntentId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'astrologicalPurpose' : IDL.Text,
    'category' : IDL.Text,
    'benefits' : IDL.Text,
    'price' : IDL.Float64,
  });
  const PujaBooking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'pujaType' : IDL.Text,
    'specialWishes' : IDL.Text,
    'gotra' : IDL.Text,
    'preferredDate' : IDL.Text,
    'templeId' : IDL.Text,
    'devoteeName' : IDL.Text,
  });
  const ReportRequest = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'pob' : IDL.Text,
    'tob' : IDL.Text,
    'status' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'reportType' : IDL.Text,
  });
  const Temple = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'deity' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'birthDate' : IDL.Text,
    'birthTime' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'birthPlace' : IDL.Text,
    'email' : IDL.Text,
    'gotra' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VirtualTempleConfig = IDL.Record({
    'background' : IDL.Text,
    'decorStyle' : IDL.Text,
    'userId' : IDL.Principal,
    'updatedAt' : Time,
    'items' : IDL.Vec(IDL.Text),
    'deity' : IDL.Text,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBhajan' : IDL.Func([BhajanEntry], [], []),
    'addHolyBookEntry' : IDL.Func([HolyBookEntry], [], []),
    'addUserPrasadDeliveryRequest' : IDL.Func([PrasadDeliveryRequest], [], []),
    'addVratKatha' : IDL.Func([VratKathaEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAstrologerProfile' : IDL.Func([AstrologerProfile], [], []),
    'createBusinessNameRecord' : IDL.Func([BusinessNameRecord], [], []),
    'createChadhavaOffering' : IDL.Func([ChadhavaOffering], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createConsultationAppointment' : IDL.Func(
        [ConsultationAppointment],
        [],
        [],
      ),
    'createDevotionalContent' : IDL.Func([DevotionalContent], [], []),
    'createNumerologyRecord' : IDL.Func([NumerologyRecord], [], []),
    'createOrder' : IDL.Func([Order], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'createPujaBooking' : IDL.Func([PujaBooking], [], []),
    'createReportRequest' : IDL.Func([ReportRequest], [], []),
    'createTemple' : IDL.Func([Temple], [], []),
    'deleteBhajan' : IDL.Func([IDL.Text], [], []),
    'deleteDevotionalContent' : IDL.Func([IDL.Text], [], []),
    'deleteHolyBookEntry' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteVratKatha' : IDL.Func([IDL.Text], [], []),
    'getAllAstrologerProfiles' : IDL.Func(
        [],
        [IDL.Vec(AstrologerProfile)],
        ['query'],
      ),
    'getAllConsultationAppointments' : IDL.Func(
        [],
        [IDL.Vec(ConsultationAppointment)],
        ['query'],
      ),
    'getAllDeliveryRequests' : IDL.Func(
        [],
        [
          IDL.Vec(IDL.Tuple(IDL.Text, PrasadDeliveryRequest)),
          IDL.Vec(IDL.Tuple(IDL.Text, PujaBooking)),
        ],
        ['query'],
      ),
    'getAllDevotionalContents' : IDL.Func(
        [],
        [IDL.Vec(DevotionalContent)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllTemples' : IDL.Func([], [IDL.Vec(Temple)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAstrologerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AstrologerProfile)],
        ['query'],
      ),
    'getBhajanById' : IDL.Func([IDL.Text], [IDL.Opt(BhajanEntry)], ['query']),
    'getBhajans' : IDL.Func([], [IDL.Vec(BhajanEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevotionalContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DevotionalContent)],
        ['query'],
      ),
    'getHolyBookEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HolyBookEntry)],
        ['query'],
      ),
    'getHolyBookEntryById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HolyBookEntry)],
        ['query'],
      ),
    'getPendingPrasadDeliveries' : IDL.Func(
        [],
        [IDL.Vec(PrasadDeliveryRequest)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserBusinessNameRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BusinessNameRecord)],
        ['query'],
      ),
    'getUserChadhavaOfferings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChadhavaOffering)],
        ['query'],
      ),
    'getUserConsultationAppointments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ConsultationAppointment)],
        ['query'],
      ),
    'getUserNumerologyRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NumerologyRecord)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserPrasadDeliveryRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PrasadDeliveryRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserPujaBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PujaBooking)],
        ['query'],
      ),
    'getUserReportRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReportRequest)],
        ['query'],
      ),
    'getVirtualTempleConfig' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VirtualTempleConfig)],
        ['query'],
      ),
    'getVratKathaById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VratKathaEntry)],
        ['query'],
      ),
    'getVratKathas' : IDL.Func([], [IDL.Vec(VratKathaEntry)], ['query']),
    'getWalletBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getWalletTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'handlePujaBooking' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'rechargeWallet' : IDL.Func(
        [IDL.Principal, IDL.Float64, WalletTransaction],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVirtualTempleConfig' : IDL.Func([VirtualTempleConfig], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBhajan' : IDL.Func([BhajanEntry], [], []),
    'updateConsultationAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateDevotionalContent' : IDL.Func([DevotionalContent], [], []),
    'updateHolyBookEntry' : IDL.Func([HolyBookEntry], [], []),
    'updateOrderPaymentStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePrasadDeliveryStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateReportRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateVratKatha' : IDL.Func([VratKathaEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };