/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AstrologerProfile {
  'id' : string,
  'bio' : string,
  'name' : string,
  'createdAt' : Time,
  'languages' : Array<string>,
  'experienceYears' : bigint,
  'perMinuteRate' : number,
  'rating' : number,
  'specializations' : Array<string>,
}
export interface BhajanEntry {
  'id' : string,
  'title' : string,
  'audioBase64' : string,
  'createdAt' : Time,
  'lyricsText' : string,
  'artist' : string,
  'deity' : string,
}
export interface BusinessNameRecord {
  'id' : string,
  'result' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'businessName' : string,
}
export interface ChadhavaOffering {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'templeId' : string,
  'items' : Array<string>,
}
export interface ConsultationAppointment {
  'id' : string,
  'status' : string,
  'topic' : string,
  'astrologerId' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'preferredDateTime' : string,
  'notes' : string,
  'specialQuestions' : string,
}
export interface DevotionalContent {
  'id' : string,
  'title' : string,
  'lyrics' : string,
  'contentType' : string,
  'createdAt' : Time,
  'language' : string,
  'deity' : string,
}
export interface HolyBookEntry {
  'id' : string,
  'bookTitle' : string,
  'shlokaText' : string,
  'bookCategory' : string,
  'audioBase64' : string,
  'trackNumber' : bigint,
  'createdAt' : Time,
  'chapterTitle' : string,
}
export interface NumerologyRecord {
  'id' : string,
  'dob' : string,
  'result' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export interface Order {
  'id' : string,
  'total' : number,
  'paymentStatus' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'stripePaymentIntentId' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface PrasadDeliveryRequest {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'mobileNumber' : string,
  'address' : string,
  'templeId' : string,
}
export interface Product {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'stock' : bigint,
  'astrologicalPurpose' : string,
  'category' : string,
  'benefits' : string,
  'price' : number,
}
export interface PujaBooking {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'pujaType' : string,
  'specialWishes' : string,
  'gotra' : string,
  'preferredDate' : string,
  'templeId' : string,
  'devoteeName' : string,
}
export interface ReportRequest {
  'id' : string,
  'dob' : string,
  'pob' : string,
  'tob' : string,
  'status' : string,
  'content' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'reportType' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Temple {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'deity' : string,
  'location' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'birthDate' : string,
  'birthTime' : string,
  'name' : string,
  'createdAt' : Time,
  'birthPlace' : string,
  'email' : string,
  'gotra' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VirtualTempleConfig {
  'background' : string,
  'decorStyle' : string,
  'userId' : Principal,
  'updatedAt' : Time,
  'items' : Array<string>,
  'deity' : string,
}
export interface VratKathaEntry {
  'id' : string,
  'title' : string,
  'audioBase64' : string,
  'storyText' : string,
  'createdAt' : Time,
  'festivalName' : string,
}
export interface WalletTransaction {
  'id' : string,
  'transactionType' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'amount' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  /**
   * / Admin-only: list all user profiles.
   */
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: add a new bhajan entry.
   */
  'addBhajan' : ActorMethod<[BhajanEntry], undefined>,
  /**
   * / Admin-only: add a new holy book entry.
   */
  'addHolyBookEntry' : ActorMethod<[HolyBookEntry], undefined>,
  /**
   * / Authenticated users can submit a prasad delivery request for themselves.
   */
  'addUserPrasadDeliveryRequest' : ActorMethod<
    [PrasadDeliveryRequest],
    undefined
  >,
  /**
   * / Admin-only: add a new vrat katha entry.
   */
  'addVratKatha' : ActorMethod<[VratKathaEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin-only: create an astrologer profile.
   */
  'createAstrologerProfile' : ActorMethod<[AstrologerProfile], undefined>,
  /**
   * / Authenticated users can create a business name analysis for themselves.
   */
  'createBusinessNameRecord' : ActorMethod<[BusinessNameRecord], undefined>,
  /**
   * / Authenticated users can submit a chadhava offering for themselves.
   */
  'createChadhavaOffering' : ActorMethod<[ChadhavaOffering], undefined>,
  /**
   * / Authenticated users can create a Stripe checkout session (e.g. for payment).
   */
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Authenticated users can book a consultation appointment for themselves.
   */
  'createConsultationAppointment' : ActorMethod<
    [ConsultationAppointment],
    undefined
  >,
  /**
   * / Admin-only: create a devotional content entry.
   */
  'createDevotionalContent' : ActorMethod<[DevotionalContent], undefined>,
  /**
   * / Authenticated users can create a numerology analysis for themselves.
   */
  'createNumerologyRecord' : ActorMethod<[NumerologyRecord], undefined>,
  /**
   * / Authenticated users can place an order for themselves.
   */
  'createOrder' : ActorMethod<[Order], undefined>,
  /**
   * / Admin-only: create a product.
   */
  'createProduct' : ActorMethod<[Product], undefined>,
  /**
   * / Authenticated users can create a puja booking for themselves.
   */
  'createPujaBooking' : ActorMethod<[PujaBooking], undefined>,
  /**
   * / Authenticated users can request a report for themselves.
   */
  'createReportRequest' : ActorMethod<[ReportRequest], undefined>,
  /**
   * / Admin-only: create a temple entry.
   */
  'createTemple' : ActorMethod<[Temple], undefined>,
  /**
   * / Admin-only: delete a bhajan entry.
   */
  'deleteBhajan' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: delete a devotional content entry.
   */
  'deleteDevotionalContent' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: delete a holy book entry.
   */
  'deleteHolyBookEntry' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: delete a product.
   */
  'deleteProduct' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: delete a vrat katha entry.
   */
  'deleteVratKatha' : ActorMethod<[string], undefined>,
  /**
   * / Public: anyone may browse astrologer profiles.
   */
  'getAllAstrologerProfiles' : ActorMethod<[], Array<AstrologerProfile>>,
  /**
   * / Admin-only: list all appointments (for astrologer/admin dashboard).
   */
  'getAllConsultationAppointments' : ActorMethod<
    [],
    Array<ConsultationAppointment>
  >,
  /**
   * / Admin-only: get all delivery requests and puja bookings.
   */
  'getAllDeliveryRequests' : ActorMethod<
    [],
    [Array<[string, PrasadDeliveryRequest]>, Array<[string, PujaBooking]>]
  >,
  /**
   * / Public: anyone may browse devotional content.
   */
  'getAllDevotionalContents' : ActorMethod<[], Array<DevotionalContent>>,
  /**
   * / Public: anyone may browse products.
   */
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Public: anyone may browse temples.
   */
  'getAllTemples' : ActorMethod<[], Array<Temple>>,
  /**
   * / Admin-only: list all user profiles.
   */
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  /**
   * / Public: get a single astrologer profile by id.
   */
  'getAstrologerProfile' : ActorMethod<[string], [] | [AstrologerProfile]>,
  /**
   * / Public: get a single bhajan entry by id.
   */
  'getBhajanById' : ActorMethod<[string], [] | [BhajanEntry]>,
  /**
   * / Public: anyone may browse bhajan entries.
   */
  'getBhajans' : ActorMethod<[], Array<BhajanEntry>>,
  /**
   * / Get the calling user's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Public: get a single devotional content entry.
   */
  'getDevotionalContent' : ActorMethod<[string], [] | [DevotionalContent]>,
  /**
   * / Public: anyone may browse holy book entries, optionally filtered by bookTitle.
   */
  'getHolyBookEntries' : ActorMethod<[string], Array<HolyBookEntry>>,
  /**
   * / Public: get a single holy book entry by id.
   */
  'getHolyBookEntryById' : ActorMethod<[string], [] | [HolyBookEntry]>,
  /**
   * / Admin-only: list all pending prasad deliveries.
   */
  'getPendingPrasadDeliveries' : ActorMethod<[], Array<PrasadDeliveryRequest>>,
  /**
   * / Public: get a single product.
   */
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  /**
   * / Authenticated users can check a Stripe session status (e.g. after checkout).
   */
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Users may only fetch their own business name records; admins may fetch any.
   */
  'getUserBusinessNameRecords' : ActorMethod<
    [Principal],
    Array<BusinessNameRecord>
  >,
  /**
   * / Users may only fetch their own offerings; admins may fetch any user's offerings.
   */
  'getUserChadhavaOfferings' : ActorMethod<
    [Principal],
    Array<ChadhavaOffering>
  >,
  /**
   * / Users may only fetch their own appointments; admins may fetch any user's.
   */
  'getUserConsultationAppointments' : ActorMethod<
    [Principal],
    Array<ConsultationAppointment>
  >,
  /**
   * / Users may only fetch their own numerology records; admins may fetch any.
   */
  'getUserNumerologyRecords' : ActorMethod<
    [Principal],
    Array<NumerologyRecord>
  >,
  /**
   * / Users may only fetch their own orders; admins may fetch any user's.
   */
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  /**
   * / Users may only fetch their own delivery requests; admins may fetch any.
   */
  'getUserPrasadDeliveryRequests' : ActorMethod<
    [Principal],
    Array<PrasadDeliveryRequest>
  >,
  /**
   * / Fetch another user's profile. Users may only fetch their own; admins may fetch any.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Users may only fetch their own bookings; admins may fetch any user's bookings.
   */
  'getUserPujaBookings' : ActorMethod<[Principal], Array<PujaBooking>>,
  /**
   * / Users may only fetch their own report requests; admins may fetch any user's.
   */
  'getUserReportRequests' : ActorMethod<[Principal], Array<ReportRequest>>,
  /**
   * / Users may only fetch their own temple config; admins may fetch any.
   */
  'getVirtualTempleConfig' : ActorMethod<
    [Principal],
    [] | [VirtualTempleConfig]
  >,
  /**
   * / Public: get a single vrat katha entry by id.
   */
  'getVratKathaById' : ActorMethod<[string], [] | [VratKathaEntry]>,
  /**
   * / Public: anyone may browse vrat katha entries.
   */
  'getVratKathas' : ActorMethod<[], Array<VratKathaEntry>>,
  /**
   * / Authenticated users can get their own wallet balance; admins can get any.
   */
  'getWalletBalance' : ActorMethod<[Principal], number>,
  /**
   * / Authenticated users can get their own transaction history; admins can get any.
   */
  'getWalletTransactions' : ActorMethod<[Principal], Array<WalletTransaction>>,
  /**
   * / Admin-only: update the status of a puja booking.
   */
  'handlePujaBooking' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Public: check whether Stripe has been configured.
   */
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / Authenticated users can add funds to their own wallet (recharge).
   */
  'rechargeWallet' : ActorMethod<
    [Principal, number, WalletTransaction],
    undefined
  >,
  /**
   * / Save / update the calling user's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Authenticated users can save their own virtual temple configuration.
   */
  'saveVirtualTempleConfig' : ActorMethod<[VirtualTempleConfig], undefined>,
  /**
   * / Admin-only: set the Stripe configuration.
   */
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Admin-only: update an existing bhajan entry.
   */
  'updateBhajan' : ActorMethod<[BhajanEntry], undefined>,
  /**
   * / Admin-only: update appointment status and notes.
   */
  'updateConsultationAppointment' : ActorMethod<
    [string, string, string],
    undefined
  >,
  /**
   * / Admin-only: update an existing devotional content entry.
   */
  'updateDevotionalContent' : ActorMethod<[DevotionalContent], undefined>,
  /**
   * / Admin-only: update an existing holy book entry.
   */
  'updateHolyBookEntry' : ActorMethod<[HolyBookEntry], undefined>,
  /**
   * / Admin-only: update order payment status.
   */
  'updateOrderPaymentStatus' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Admin-only: update the status of a prasad delivery request.
   */
  'updatePrasadDeliveryStatus' : ActorMethod<[string, string], undefined>,
  /**
   * / Admin-only: update a product.
   */
  'updateProduct' : ActorMethod<[Product], undefined>,
  /**
   * / Admin-only: update report status and content.
   */
  'updateReportRequest' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Admin-only: update an existing vrat katha entry.
   */
  'updateVratKatha' : ActorMethod<[VratKathaEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];