import type {
  ChoghadiyaQuality,
  FestivalEntry,
  HoraPlanetInfo,
  PanchangCity,
  RegionalTerminology,
} from "./panchangTypes";

// ── Cities ────────────────────────────────────────────────────────────────────────────

export const CITIES: PanchangCity[] = [
  // ── Delhi / NCR
  {
    id: "delhi",
    name: "New Delhi",
    nameHi: "नई दिल्ली",
    lat: 28.6139,
    lng: 77.209,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Delhi / NCR",
  },
  {
    id: "gurugram",
    name: "Gurugram",
    nameHi: "गुरुग्राम",
    lat: 28.4595,
    lng: 77.0266,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Delhi / NCR",
  },
  {
    id: "noida",
    name: "Noida",
    nameHi: "नोएडा",
    lat: 28.5355,
    lng: 77.391,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Delhi / NCR",
  },
  {
    id: "ghaziabad",
    name: "Ghaziabad",
    nameHi: "गाजियाबाद",
    lat: 28.6692,
    lng: 77.4538,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Delhi / NCR",
  },
  // ── Maharashtra
  {
    id: "mumbai",
    name: "Mumbai",
    nameHi: "मुंबई",
    lat: 19.076,
    lng: 72.8777,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Maharashtra",
  },
  {
    id: "pune",
    name: "Pune",
    nameHi: "पुणे",
    lat: 18.5204,
    lng: 73.8567,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Maharashtra",
  },
  {
    id: "nasik",
    name: "Nashik",
    nameHi: "नाशिक",
    lat: 19.9975,
    lng: 73.7898,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Maharashtra",
  },
  {
    id: "nagpur",
    name: "Nagpur",
    nameHi: "नागपुर",
    lat: 21.1458,
    lng: 79.0882,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Maharashtra",
  },
  {
    id: "aurangabad",
    name: "Aurangabad",
    nameHi: "औरंगाबाद",
    lat: 19.8762,
    lng: 75.3433,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Maharashtra",
  },
  {
    id: "kalyan",
    name: "Kalyan",
    nameHi: "कल्याण",
    lat: 19.2403,
    lng: 73.1305,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Maharashtra",
  },
  // ── Karnataka
  {
    id: "bangalore",
    name: "Bengaluru",
    nameHi: "बेंगलुरु",
    lat: 12.9716,
    lng: 77.5946,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Karnataka",
  },
  {
    id: "mysuru",
    name: "Mysuru",
    nameHi: "मैसूर",
    lat: 12.2958,
    lng: 76.6394,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Karnataka",
  },
  {
    id: "hubballi",
    name: "Hubballi",
    nameHi: "हुबली",
    lat: 15.3647,
    lng: 75.124,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Karnataka",
  },
  {
    id: "mangaluru",
    name: "Mangaluru",
    nameHi: "मंगलुरु",
    lat: 12.9141,
    lng: 74.856,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Karnataka",
  },
  // ── Tamil Nadu
  {
    id: "chennai",
    name: "Chennai",
    nameHi: "चेन्नई",
    lat: 13.0827,
    lng: 80.2707,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Tamil Nadu",
  },
  {
    id: "madurai",
    name: "Madurai",
    nameHi: "मदुरई",
    lat: 9.9252,
    lng: 78.1198,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Tamil Nadu",
  },
  {
    id: "coimbatore",
    name: "Coimbatore",
    nameHi: "कोयंबटूर",
    lat: 11.0168,
    lng: 76.9558,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Tamil Nadu",
  },
  {
    id: "tirupati",
    name: "Tirupati",
    nameHi: "तिरुपति",
    lat: 13.6288,
    lng: 79.4192,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Tamil Nadu",
  },
  // ── Gujarat
  {
    id: "ahmedabad",
    name: "Ahmedabad",
    nameHi: "अहमदाबाद",
    lat: 23.0225,
    lng: 72.5714,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Gujarat",
  },
  {
    id: "surat",
    name: "Surat",
    nameHi: "सूरत",
    lat: 21.1702,
    lng: 72.8311,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Gujarat",
  },
  {
    id: "vadodara",
    name: "Vadodara",
    nameHi: "वडोदरा",
    lat: 22.3072,
    lng: 73.1812,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Gujarat",
  },
  {
    id: "rajkot",
    name: "Rajkot",
    nameHi: "राजकोट",
    lat: 22.3039,
    lng: 70.8022,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Gujarat",
  },
  {
    id: "dwarka",
    name: "Dwarka",
    nameHi: "द्वारका",
    lat: 22.2394,
    lng: 68.9678,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Gujarat",
  },
  // ── Rajasthan
  {
    id: "jaipur",
    name: "Jaipur",
    nameHi: "जयपुर",
    lat: 26.9124,
    lng: 75.7873,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Rajasthan",
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    nameHi: "जोधपुर",
    lat: 26.2389,
    lng: 73.0243,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Rajasthan",
  },
  {
    id: "udaipur",
    name: "Udaipur",
    nameHi: "उदयपुर",
    lat: 24.5854,
    lng: 73.7125,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Rajasthan",
  },
  {
    id: "pushkar",
    name: "Pushkar",
    nameHi: "पुष्कर",
    lat: 26.4897,
    lng: 74.5511,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Rajasthan",
  },
  {
    id: "ajmer",
    name: "Ajmer",
    nameHi: "अजमेर",
    lat: 26.4499,
    lng: 74.6399,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Rajasthan",
  },
  // ── Uttar Pradesh
  {
    id: "varanasi",
    name: "Varanasi",
    nameHi: "वाराणसी",
    lat: 25.3176,
    lng: 82.9739,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "lucknow",
    name: "Lucknow",
    nameHi: "लखनऊ",
    lat: 26.8467,
    lng: 80.9462,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "prayagraj",
    name: "Prayagraj",
    nameHi: "प्रयागराज",
    lat: 25.4358,
    lng: 81.8463,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "mathura",
    name: "Mathura",
    nameHi: "मथुरा",
    lat: 27.4924,
    lng: 77.6737,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "vrindavan",
    name: "Vrindavan",
    nameHi: "वृन्दावन",
    lat: 27.5694,
    lng: 77.672,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "ayodhya",
    name: "Ayodhya",
    nameHi: "अयोध्या",
    lat: 26.7922,
    lng: 82.1998,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "agra",
    name: "Agra",
    nameHi: "आगरा",
    lat: 27.1767,
    lng: 78.0081,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "meerut",
    name: "Meerut",
    nameHi: "मेरठ",
    lat: 28.9845,
    lng: 77.7064,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "mardanpur",
    name: "Mardanpur",
    nameHi: "मर्दानपुर",
    lat: 25.92,
    lng: 81.1,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  {
    id: "rampura",
    name: "Rampura",
    nameHi: "रामपुरा",
    lat: 27.45,
    lng: 77.1,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Uttar Pradesh",
  },
  // ── Madhya Pradesh
  {
    id: "bhopal",
    name: "Bhopal",
    nameHi: "भोपाल",
    lat: 23.2599,
    lng: 77.4126,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Madhya Pradesh",
  },
  {
    id: "indore",
    name: "Indore",
    nameHi: "इंदौर",
    lat: 22.7196,
    lng: 75.8577,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Madhya Pradesh",
  },
  {
    id: "ujjain",
    name: "Ujjain",
    nameHi: "उज्जैन",
    lat: 23.1765,
    lng: 75.7885,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Madhya Pradesh",
  },
  {
    id: "omkareshwar",
    name: "Omkareshwar",
    nameHi: "ओंकारेश्वर",
    lat: 22.2407,
    lng: 76.1517,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Madhya Pradesh",
  },
  {
    id: "jabalpur",
    name: "Jabalpur",
    nameHi: "जबलपुर",
    lat: 23.1815,
    lng: 79.9864,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Madhya Pradesh",
  },
  {
    id: "nara",
    name: "Narsinghpur",
    nameHi: "नरसिंहपुर",
    lat: 22.9542,
    lng: 79.1947,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Madhya Pradesh",
  },
  // ── Punjab
  {
    id: "amritsar",
    name: "Amritsar",
    nameHi: "अमृतसर",
    lat: 31.634,
    lng: 74.8723,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Punjab",
  },
  {
    id: "ludhiana",
    name: "Ludhiana",
    nameHi: "लुधियाना",
    lat: 30.901,
    lng: 75.8573,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Punjab",
  },
  {
    id: "chandigarh",
    name: "Chandigarh",
    nameHi: "चंडीगढ़",
    lat: 30.7333,
    lng: 76.7794,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Punjab",
  },
  {
    id: "jalandhar",
    name: "Jalandhar",
    nameHi: "जालंधर",
    lat: 31.326,
    lng: 75.5762,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Punjab",
  },
  // ── West Bengal
  {
    id: "kolkata",
    name: "Kolkata",
    nameHi: "कोलकाता",
    lat: 22.5726,
    lng: 88.3639,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "West Bengal",
  },
  {
    id: "haora",
    name: "Haora (Howrah)",
    nameHi: "हावड़ा",
    lat: 22.5958,
    lng: 88.2636,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "West Bengal",
  },
  {
    id: "asansol",
    name: "Asansol",
    nameHi: "आसनसोल",
    lat: 23.6888,
    lng: 86.9661,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "West Bengal",
  },
  // ── Telangana
  {
    id: "hyderabad",
    name: "Hyderabad",
    nameHi: "हैदराबाद",
    lat: 17.385,
    lng: 78.4867,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Telangana",
  },
  {
    id: "vishakhapatnam",
    name: "Visakhapatnam",
    nameHi: "विशाखापट्नम",
    lat: 17.6868,
    lng: 83.2185,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Telangana",
  },
  // ── Kerala
  {
    id: "kochi",
    name: "Kochi",
    nameHi: "कोच्चि",
    lat: 9.9312,
    lng: 76.2673,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Kerala",
  },
  {
    id: "thiruvananthapuram",
    name: "Thiruvananthapuram",
    nameHi: "तिरुवनंतपुरम",
    lat: 8.5241,
    lng: 76.9366,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Kerala",
  },
  {
    id: "guruvayur",
    name: "Guruvayur",
    nameHi: "गुरुवायुर",
    lat: 10.5943,
    lng: 76.0416,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Kerala",
  },
  // ── Bihar
  {
    id: "patna",
    name: "Patna",
    nameHi: "पटना",
    lat: 25.5941,
    lng: 85.1376,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Bihar",
  },
  {
    id: "gaya",
    name: "Gaya (Bodh Gaya)",
    nameHi: "गया",
    lat: 24.7914,
    lng: 84.9994,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Bihar",
  },
  {
    id: "vaishali",
    name: "Vaishali",
    nameHi: "वैशाली",
    lat: 25.9959,
    lng: 85.1283,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Bihar",
  },
  // ── Jharkhand
  {
    id: "jamshedpur",
    name: "Jamshedpur",
    nameHi: "जमशेदपुर",
    lat: 22.8046,
    lng: 86.2029,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Jharkhand",
  },
  // ── Haryana
  {
    id: "faridabad",
    name: "Faridabad",
    nameHi: "फरीदाबाद",
    lat: 28.4089,
    lng: 77.3178,
    timezone: "Asia/Kolkata",
    offset: "+5:30",
    stateName: "Haryana",
  },
];

// ── Cities grouped by State ───────────────────────────────────────────────────

export const CITIES_BY_STATE: Record<string, PanchangCity[]> = CITIES.reduce(
  (acc, city) => {
    const state = city.stateName ?? "Other";
    if (!acc[state]) acc[state] = [];
    acc[state].push(city);
    return acc;
  },
  {} as Record<string, PanchangCity[]>,
);
// ── Tithi Names ───────────────────────────────────────────────────────────────

const HINDI_TITHIS = [
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

const TAMIL_TITHIS = [
  "Pirathamai",
  "Thuthiyai",
  "Thiruthiyai",
  "Sathurthi",
  "Panjami",
  "Shasti",
  "Sapthami",
  "Astami",
  "Navami",
  "Thasami",
  "Egadashi",
  "Duvadasi",
  "Thirayodasi",
  "Sathuradasi",
  "Pournami",
  "Pirathamai",
  "Thuthiyai",
  "Thiruthiyai",
  "Sathurthi",
  "Panjami",
  "Shasti",
  "Sapthami",
  "Astami",
  "Navami",
  "Thasami",
  "Egadashi",
  "Duvadasi",
  "Thirayodasi",
  "Sathuradasi",
  "Amavasai",
];

const KANNADA_TITHIS = [
  "Padya",
  "Bidige",
  "Tadige",
  "Chouti",
  "Panchami",
  "Shashti",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Hunnime",
  "Padya",
  "Bidige",
  "Tadige",
  "Chouti",
  "Panchami",
  "Shashti",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

const TELUGU_TITHIS = [
  "Paadyami",
  "Vidiya",
  "Tadiya",
  "Chavithi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Pournami",
  "Paadyami",
  "Vidiya",
  "Tadiya",
  "Chavithi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

const MALAYALAM_TITHIS = [
  "Prathamam",
  "Dwithiyam",
  "Trithiyam",
  "Chathurthi",
  "Panchami",
  "Shasht",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Thrayodashi",
  "Chathurdashi",
  "Pournami",
  "Prathamam",
  "Dwithiyam",
  "Trithiyam",
  "Chathurthi",
  "Panchami",
  "Shasht",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Thrayodashi",
  "Chathurdashi",
  "Amavasya",
];

const GUJARATI_TITHIS = [
  "Ekam",
  "Bij",
  "Trij",
  "Choth",
  "Pancham",
  "Chhath",
  "Satam",
  "Aatham",
  "Nom",
  "Dasam",
  "Agiyaras",
  "Baras",
  "Teras",
  "Chaudas",
  "Poonam",
  "Ekam",
  "Bij",
  "Trij",
  "Choth",
  "Pancham",
  "Chhath",
  "Satam",
  "Aatham",
  "Nom",
  "Dasam",
  "Agiyaras",
  "Baras",
  "Teras",
  "Chaudas",
  "Amaas",
];

const MARATHI_TITHIS = [
  "Pratipad",
  "Dvitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dvadashi",
  "Trayodashi",
  "Chaturdashi",
  "Pournima",
  "Pratipad",
  "Dvitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dvadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

const BENGALI_TITHIS = [
  "Pratipad",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
  "Pratipad",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

const ODIA_TITHIS = [
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

const NEPALI_TITHIS = [
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
  "Pratipada",
  "Dwitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Aunsi",
];

const ISKCON_TITHIS = [
  "Pratipada",
  "Dvitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dvadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
  "Pratipada",
  "Dvitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dvadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

// ── Nakshatra Names ───────────────────────────────────────────────────────────

const HINDI_NAKSHATRAS = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishtha",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];

const TAMIL_NAKSHATRAS = [
  "Aswini",
  "Bharani",
  "Karthigai",
  "Rohini",
  "Mirugasirisham",
  "Thiruvathirai",
  "Punarpoosam",
  "Poosam",
  "Ayilyam",
  "Magam",
  "Pooram",
  "Uthiram",
  "Hastham",
  "Chithirai",
  "Swathi",
  "Visakam",
  "Anusham",
  "Kettai",
  "Moolam",
  "Pooradam",
  "Uthiradam",
  "Thiruvonam",
  "Avittam",
  "Sathayam",
  "Poorattathi",
  "Uthirattathi",
  "Revathi",
];

const KANNADA_NAKSHATRAS = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrugashira",
  "Aridra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Makha",
  "Pubba",
  "Uttara Phalguni",
  "Hasta",
  "Chitta",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishtha",
  "Shatabhisha",
  "Purva Bhadra",
  "Uttara Bhadra",
  "Revati",
];

const TELUGU_NAKSHATRAS = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigasira",
  "Ardra",
  "Punarvasu",
  "Pushyami",
  "Aslesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Moola",
  "Purvashadha",
  "Uttarashadha",
  "Shravana",
  "Dhanishtha",
  "Shatabhisha",
  "Purva Bhadra",
  "Uttara Bhadra",
  "Revati",
];

const MALAYALAM_NAKSHATRAS = [
  "Ashwathi",
  "Bharani",
  "Karthika",
  "Rohini",
  "Makayiram",
  "Thiruvathira",
  "Punartham",
  "Pooyam",
  "Aayilyam",
  "Makam",
  "Pooram",
  "Uthram",
  "Atham",
  "Chithra",
  "Chothi",
  "Vishakham",
  "Anizham",
  "Thrikketta",
  "Moolam",
  "Pooradam",
  "Uthradom",
  "Thiruvonam",
  "Avittom",
  "Chathayam",
  "Pooruruttathi",
  "Uthruttathi",
  "Revathi",
];

const GENERIC_NAKSHATRAS = HINDI_NAKSHATRAS;

// ── Rashi Names ───────────────────────────────────────────────────────────────

const HINDI_RASHIS = [
  "Mesha",
  "Vrishabha",
  "Mithuna",
  "Karka",
  "Simha",
  "Kanya",
  "Tula",
  "Vrischika",
  "Dhanu",
  "Makara",
  "Kumbha",
  "Meena",
];

const TAMIL_RASHIS = [
  "Mesham",
  "Rishabam",
  "Midhunam",
  "Kadagam",
  "Simmam",
  "Kanni",
  "Thulam",
  "Viruchigam",
  "Dhanusu",
  "Magaram",
  "Kumbam",
  "Meenam",
];

const KANNADA_RASHIS = [
  "Mesha",
  "Vrushabha",
  "Mithuna",
  "Kataka",
  "Simha",
  "Kanya",
  "Tula",
  "Vrushchika",
  "Dhanu",
  "Makara",
  "Kumbha",
  "Meena",
];

const TELUGU_RASHIS = [
  "Mesha",
  "Vrushabha",
  "Mithuna",
  "Karkitaka",
  "Simha",
  "Kanya",
  "Tula",
  "Vrushchika",
  "Dhanu",
  "Makara",
  "Kumbha",
  "Meenam",
];

const MALAYALAM_RASHIS = [
  "Medam",
  "Idavam",
  "Midhunam",
  "Karkidakam",
  "Chingam",
  "Kanni",
  "Thulam",
  "Vrischikam",
  "Dhanu",
  "Makaram",
  "Kumbham",
  "Meenam",
];

const GENERIC_RASHIS = HINDI_RASHIS;

// ── Weekday Names ─────────────────────────────────────────────────────────────

const HINDI_WEEKDAYS = [
  "Ravivaar",
  "Somvaar",
  "Mangalvaar",
  "Budhvaar",
  "Guruvaar",
  "Shukravaar",
  "Shanivaar",
];
const TAMIL_WEEKDAYS = [
  "Nayiru",
  "Thingal",
  "Sevvai",
  "Budhan",
  "Viyaazhan",
  "Velli",
  "Sani",
];
const KANNADA_WEEKDAYS = [
  "Bhanuvaara",
  "Somavaara",
  "Mangalavaara",
  "Budhavaara",
  "Guruvaar",
  "Shukravaara",
  "Shanivaara",
];
const TELUGU_WEEKDAYS = [
  "Adivaram",
  "Somavaram",
  "Mangalavaram",
  "Budhavaram",
  "Guruvaram",
  "Shukravaram",
  "Shanivaram",
];
const MALAYALAM_WEEKDAYS = [
  "Njaayar",
  "Thinkal",
  "Chovva",
  "Budhan",
  "Vyazham",
  "Velli",
  "Shani",
];
const GENERIC_WEEKDAYS = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

// ── Paksha Names ──────────────────────────────────────────────────────────────

const HINDI_PAKSHAS = ["Shukla Paksha", "Krishna Paksha"];
const TAMIL_PAKSHAS = ["Valarpirai", "Theipirai"];
const KANNADA_PAKSHAS = ["Shukla Paksha", "Krishna Paksha"];
const GENERIC_PAKSHAS = ["Shukla", "Krishna"];
const ISKCON_PAKSHAS = ["Gaura Paksha", "Krishna Paksha"];

// ── Month Names ───────────────────────────────────────────────────────────────

const HINDI_MONTHS = [
  "Chaitra",
  "Vaishakha",
  "Jyeshtha",
  "Ashadha",
  "Shravana",
  "Bhadrapada",
  "Ashvina",
  "Kartika",
  "Margashirsha",
  "Pausha",
  "Magha",
  "Phalguna",
];

const TAMIL_MONTHS = [
  "Chittirai",
  "Vaikasi",
  "Aani",
  "Aadi",
  "Aavani",
  "Purattasi",
  "Aippasi",
  "Karthigai",
  "Margazhi",
  "Thai",
  "Maasi",
  "Panguni",
];

const KANNADA_MONTHS = [
  "Chaitra",
  "Vaishakha",
  "Jyeshtha",
  "Ashadha",
  "Shravana",
  "Bhadrapada",
  "Ashvina",
  "Kartika",
  "Margashirsha",
  "Pausha",
  "Magha",
  "Phalguna",
];

const TELUGU_MONTHS = [
  "Chaitra",
  "Vaishakha",
  "Jyeshtha",
  "Ashadha",
  "Shravana",
  "Bhadrapada",
  "Ashwayuja",
  "Kartika",
  "Margashira",
  "Pushya",
  "Magha",
  "Phalguna",
];

const MALAYALAM_MONTHS = [
  "Chingam",
  "Kanni",
  "Thulam",
  "Vrischikam",
  "Dhanu",
  "Makaram",
  "Kumbham",
  "Meenam",
  "Medam",
  "Idavam",
  "Midhunam",
  "Karkidakam",
];

const GUJARATI_MONTHS = [
  "Chaitra",
  "Vaishakh",
  "Jeth",
  "Ashadh",
  "Shravan",
  "Bhadarvo",
  "Aso",
  "Kartik",
  "Magshar",
  "Posh",
  "Maha",
  "Phagun",
];

const MARATHI_MONTHS = [
  "Chaitra",
  "Vaishakha",
  "Jyeshtha",
  "Ashadha",
  "Shravana",
  "Bhadrapada",
  "Ashwin",
  "Kartik",
  "Margashirsha",
  "Paush",
  "Magh",
  "Phalguna",
];

const BENGALI_MONTHS = [
  "Baishakh",
  "Jyaishtha",
  "Asharh",
  "Shraban",
  "Bhadra",
  "Ashwin",
  "Kartik",
  "Agrahayan",
  "Poush",
  "Magh",
  "Falgun",
  "Chaitra",
];

const ODIA_MONTHS = [
  "Baishakha",
  "Jyaishtha",
  "Ashadha",
  "Shravana",
  "Bhadra",
  "Ashwina",
  "Kartika",
  "Margashira",
  "Pausha",
  "Magha",
  "Phalguna",
  "Chaitra",
];

const NEPALI_MONTHS = [
  "Baisakh",
  "Jestha",
  "Ashadh",
  "Shrawan",
  "Bhadra",
  "Ashoj",
  "Kartik",
  "Mangsir",
  "Poush",
  "Magh",
  "Falgun",
  "Chaitra",
];

const ISKCON_MONTHS = [
  "Madhurya (Vishnu)",
  "Kesava",
  "Trivikrama",
  "Vamana",
  "Sridhara",
  "Hrishikesha",
  "Padmanabha",
  "Damodara",
  "Keshava",
  "Narayana",
  "Madhava",
  "Govinda",
];

// ── Regional Terminology Map ──────────────────────────────────────────────────

export const REGIONAL_TERMINOLOGY: Record<string, RegionalTerminology> = {
  Hindi: {
    region: "Hindi",
    tithiNames: HINDI_TITHIS,
    nakshatraNames: HINDI_NAKSHATRAS,
    rashiNames: HINDI_RASHIS,
    weekdayNames: HINDI_WEEKDAYS,
    pakshaNames: HINDI_PAKSHAS,
    monthNames: HINDI_MONTHS,
  },
  Tamil: {
    region: "Tamil",
    tithiNames: TAMIL_TITHIS,
    nakshatraNames: TAMIL_NAKSHATRAS,
    rashiNames: TAMIL_RASHIS,
    weekdayNames: TAMIL_WEEKDAYS,
    pakshaNames: TAMIL_PAKSHAS,
    monthNames: TAMIL_MONTHS,
  },
  Kannada: {
    region: "Kannada",
    tithiNames: KANNADA_TITHIS,
    nakshatraNames: KANNADA_NAKSHATRAS,
    rashiNames: KANNADA_RASHIS,
    weekdayNames: KANNADA_WEEKDAYS,
    pakshaNames: KANNADA_PAKSHAS,
    monthNames: KANNADA_MONTHS,
  },
  Telugu: {
    region: "Telugu",
    tithiNames: TELUGU_TITHIS,
    nakshatraNames: TELUGU_NAKSHATRAS,
    rashiNames: TELUGU_RASHIS,
    weekdayNames: TELUGU_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: TELUGU_MONTHS,
  },
  Malayalam: {
    region: "Malayalam",
    tithiNames: MALAYALAM_TITHIS,
    nakshatraNames: MALAYALAM_NAKSHATRAS,
    rashiNames: MALAYALAM_RASHIS,
    weekdayNames: MALAYALAM_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: MALAYALAM_MONTHS,
  },
  Gujarati: {
    region: "Gujarati",
    tithiNames: GUJARATI_TITHIS,
    nakshatraNames: GENERIC_NAKSHATRAS,
    rashiNames: GENERIC_RASHIS,
    weekdayNames: GENERIC_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: GUJARATI_MONTHS,
  },
  Marathi: {
    region: "Marathi",
    tithiNames: MARATHI_TITHIS,
    nakshatraNames: GENERIC_NAKSHATRAS,
    rashiNames: GENERIC_RASHIS,
    weekdayNames: GENERIC_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: MARATHI_MONTHS,
  },
  Bengali: {
    region: "Bengali",
    tithiNames: BENGALI_TITHIS,
    nakshatraNames: GENERIC_NAKSHATRAS,
    rashiNames: GENERIC_RASHIS,
    weekdayNames: GENERIC_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: BENGALI_MONTHS,
  },
  Odia: {
    region: "Odia",
    tithiNames: ODIA_TITHIS,
    nakshatraNames: GENERIC_NAKSHATRAS,
    rashiNames: GENERIC_RASHIS,
    weekdayNames: GENERIC_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: ODIA_MONTHS,
  },
  Nepali: {
    region: "Nepali",
    tithiNames: NEPALI_TITHIS,
    nakshatraNames: GENERIC_NAKSHATRAS,
    rashiNames: GENERIC_RASHIS,
    weekdayNames: GENERIC_WEEKDAYS,
    pakshaNames: GENERIC_PAKSHAS,
    monthNames: NEPALI_MONTHS,
  },
  ISKCON: {
    region: "ISKCON",
    tithiNames: ISKCON_TITHIS,
    nakshatraNames: GENERIC_NAKSHATRAS,
    rashiNames: GENERIC_RASHIS,
    weekdayNames: GENERIC_WEEKDAYS,
    pakshaNames: ISKCON_PAKSHAS,
    monthNames: ISKCON_MONTHS,
  },
};

// ── Core Astronomy Arrays ─────────────────────────────────────────────────────

export const YOGAS: string[] = [
  "Vishkambha",
  "Priti",
  "Ayushman",
  "Saubhagya",
  "Shobhana",
  "Atiganda",
  "Sukarma",
  "Dhriti",
  "Shula",
  "Ganda",
  "Vriddhi",
  "Dhruva",
  "Vyaghata",
  "Harshana",
  "Vajra",
  "Siddhi",
  "Vyatipata",
  "Variyan",
  "Parigha",
  "Shiva",
  "Siddha",
  "Sadhya",
  "Shubha",
  "Shukla",
  "Brahma",
  "Indra",
  "Vaidhriti",
];

export const KARANAS: string[] = [
  "Kinstughna",
  "Bava",
  "Balava",
  "Kaulava",
  "Taitila",
  "Garaja",
  "Vanija",
  "Vishti",
  "Shakuni",
  "Chatushpada",
  "Nagava",
];

export const RASHIS: string[] = [
  "Mesha",
  "Vrishabha",
  "Mithuna",
  "Karka",
  "Simha",
  "Kanya",
  "Tula",
  "Vrischika",
  "Dhanu",
  "Makara",
  "Kumbha",
  "Meena",
];

export const SAMVATSARAS: string[] = [
  "Prabhava",
  "Vibhava",
  "Shukla",
  "Pramoda",
  "Prajapati",
  "Angirasa",
  "Shrimukha",
  "Bhava",
  "Yuva",
  "Dhatri",
  "Ishvara",
  "Bahudhanya",
  "Pramadhi",
  "Vikrama",
  "Vrisha",
  "Chitrabhanu",
  "Subhanu",
  "Tarana",
  "Parthiva",
  "Vyaya",
  "Sarvajit",
  "Sarvadhari",
  "Virodhi",
  "Vikrita",
  "Khara",
  "Nandana",
  "Vijaya",
  "Jaya",
  "Manmatha",
  "Durmukha",
  "Hevilambi",
  "Vilambi",
  "Vikari",
  "Sharvari",
  "Plava",
  "Shubhakrita",
  "Shobhana",
  "Krodhi",
  "Vishvavasu",
  "Parabhava",
  "Plavanga",
  "Kilaka",
  "Saumya",
  "Sadharana",
  "Virodhikrita",
  "Pariddhavi",
  "Pramadi",
  "Ananda",
  "Rakshasa",
  "Nala",
  "Pingala",
  "Kalayukti",
  "Siddharthi",
  "Raudra",
  "Durmati",
  "Dundubhi",
  "Rudhirodgari",
  "Raktakshi",
  "Krodhana",
  "Kshaya",
];

export const LUNAR_MONTHS: string[] = [
  "Chaitra",
  "Vaishakha",
  "Jyeshtha",
  "Ashadha",
  "Shravana",
  "Bhadrapada",
  "Ashvina",
  "Kartika",
  "Margashirsha",
  "Pausha",
  "Magha",
  "Phalguna",
];

// ── Choghadiya ─────────────────────────────────────────────────────────────────

/** Day choghadiya order by weekday (0=Sun … 6=Sat) */
export const CHOGHADIYA_DAY_ORDER: Record<number, string[]> = {
  0: ["Udvega", "Chara", "Labha", "Amrita", "Kala", "Shubha", "Roga", "Udvega"],
  1: ["Amrita", "Kala", "Shubha", "Roga", "Udvega", "Chara", "Labha", "Amrita"],
  2: ["Roga", "Udvega", "Chara", "Labha", "Amrita", "Kala", "Shubha", "Roga"],
  3: ["Labha", "Amrita", "Kala", "Shubha", "Roga", "Udvega", "Chara", "Labha"],
  4: ["Shubha", "Roga", "Udvega", "Chara", "Labha", "Amrita", "Kala", "Shubha"],
  5: ["Chara", "Labha", "Amrita", "Kala", "Shubha", "Roga", "Udvega", "Chara"],
  6: ["Kala", "Shubha", "Roga", "Udvega", "Chara", "Labha", "Amrita", "Kala"],
};

/** Night choghadiya order by weekday (starts after sunset) */
export const CHOGHADIYA_NIGHT_ORDER: Record<number, string[]> = {
  0: ["Shubha", "Amrita", "Chara", "Roga", "Kala", "Labha", "Udvega", "Shubha"],
  1: ["Chara", "Roga", "Kala", "Labha", "Udvega", "Shubha", "Amrita", "Chara"],
  2: ["Kala", "Labha", "Udvega", "Shubha", "Amrita", "Chara", "Roga", "Kala"],
  3: ["Udvega", "Shubha", "Amrita", "Chara", "Roga", "Kala", "Labha", "Udvega"],
  4: ["Amrita", "Chara", "Roga", "Kala", "Labha", "Udvega", "Shubha", "Amrita"],
  5: ["Roga", "Kala", "Labha", "Udvega", "Shubha", "Amrita", "Chara", "Roga"],
  6: ["Labha", "Udvega", "Shubha", "Amrita", "Chara", "Roga", "Kala", "Labha"],
};

export const CHOGHADIYA_QUALITY: Record<string, ChoghadiyaQuality> = {
  Amrita: {
    isAuspicious: true,
    isInauspicious: false,
    color: "auspicious",
    description: "Nectar — excellent for all auspicious work",
  },
  Labha: {
    isAuspicious: true,
    isInauspicious: false,
    color: "auspicious",
    description: "Gain — good for business, travel, new ventures",
  },
  Shubha: {
    isAuspicious: true,
    isInauspicious: false,
    color: "beneficial",
    description: "Auspicious — good for marriage, ceremonies, social work",
  },
  Chara: {
    isAuspicious: true,
    isInauspicious: false,
    color: "beneficial",
    description: "Movement — good for travel and change of residence",
  },
  Roga: {
    isAuspicious: false,
    isInauspicious: true,
    color: "inauspicious",
    description: "Disease — avoid health-related activities",
  },
  Udvega: {
    isAuspicious: false,
    isInauspicious: true,
    color: "warning",
    description: "Anxiety — avoid important decisions",
  },
  Kala: {
    isAuspicious: false,
    isInauspicious: true,
    color: "neutral",
    description: "Death — avoid all auspicious work",
  },
};

// ── Hora ───────────────────────────────────────────────────────────────────────

/** Chaldean sequence for hora rotation */
export const HORA_PLANET_ORDER: string[] = [
  "Sun",
  "Venus",
  "Mercury",
  "Moon",
  "Saturn",
  "Jupiter",
  "Mars",
];

export const HORA_PLANET_CHARACTER: Record<string, HoraPlanetInfo> = {
  Sun: {
    character: "Authority, leadership, vitality",
    color: "sun",
  },
  Moon: { character: "Mind, emotions, creativity", color: "moon" },
  Mars: { character: "Energy, courage, action", color: "mars" },
  Mercury: {
    character: "Business, communication, intellect",
    color: "mercury",
  },
  Jupiter: { character: "Wisdom, wealth, expansion", color: "jupiter" },
  Venus: { character: "Love, beauty, luxury", color: "venus" },
  Saturn: { character: "Discipline, karmic lessons", color: "saturn" },
};

/** Day lord of each weekday (0=Sun … 6=Sat) */
export const HORA_WEEKDAY_LORDS: string[] = [
  "Sun",
  "Moon",
  "Mars",
  "Mercury",
  "Jupiter",
  "Venus",
  "Saturn",
];

// ── Muhurat Tables ─────────────────────────────────────────────────────────────

export const DAY_MUHURATS: Array<{
  name: string;
  quality: "good" | "bad" | "neutral";
}> = [
  { name: "Rudra", quality: "bad" },
  { name: "Ahi", quality: "bad" },
  { name: "Mitra", quality: "good" },
  { name: "Pitara", quality: "bad" },
  { name: "Vasu", quality: "good" },
  { name: "Ambu", quality: "good" },
  { name: "Vishwedeva", quality: "good" },
  { name: "Vidhi", quality: "good" },
  { name: "Brahma", quality: "good" },
  { name: "Indra", quality: "good" },
  { name: "Indragni", quality: "bad" },
  { name: "Daitya", quality: "bad" },
  { name: "Varuna", quality: "good" },
  { name: "Aryama", quality: "good" },
  { name: "Bhaga", quality: "bad" },
];

export const NIGHT_MUHURATS: Array<{
  name: string;
  quality: "good" | "bad" | "neutral";
}> = [
  { name: "Ishwara", quality: "bad" },
  { name: "Ajaikapada", quality: "bad" },
  { name: "Ahirbudhnya", quality: "good" },
  { name: "Pusha", quality: "good" },
  { name: "Ashwini", quality: "good" },
  { name: "Yama", quality: "bad" },
  { name: "Agni", quality: "bad" },
  { name: "Brahma", quality: "good" },
  { name: "Chandra", quality: "good" },
  { name: "Aditi", quality: "good" },
  { name: "Brihaspati", quality: "good" },
  { name: "Vishnu", quality: "good" },
  { name: "Surya", quality: "good" },
  { name: "Tvashta", quality: "good" },
  { name: "Samirana", quality: "good" },
];

// ── Panchaka ───────────────────────────────────────────────────────────────────

export const PANCHAKA_TYPES: Record<
  string,
  { color: string; description: string }
> = {
  Shubha: {
    color: "auspicious",
    description: "Auspicious Panchaka — good for all works",
  },
  Roga: {
    color: "inauspicious",
    description: "Disease Panchaka — avoid health matters",
  },
  Mrityu: {
    color: "neutral",
    description: "Death Panchaka — avoid all auspicious work",
  },
  Agni: {
    color: "warning",
    description: "Fire Panchaka — avoid fire-related work",
  },
  Raja: {
    color: "warning",
    description: "Kingly Panchaka — good for government work",
  },
  Chora: {
    color: "inauspicious",
    description: "Thief Panchaka — be cautious of losses",
  },
};

// ── Pancha Pakshi ──────────────────────────────────────────────────────────────

export const PANCHA_PAKSHI_BIRDS: string[] = [
  "Vulture",
  "Owl",
  "Crow",
  "Cock",
  "Peacock",
];

export const PANCHA_PAKSHI_ACTIVITIES: Record<string, string> = {
  Ruling: "Very Good",
  Eating: "Good",
  Walking: "Average",
  Sleeping: "Average/Bad",
  Dying: "Very Bad",
};

// ── Glossary ───────────────────────────────────────────────────────────────────

export const GLOSSARY: Record<string, string> = {
  Tithi:
    "Lunar day — 1/30th of a synodic month; governs the quality of the day for ceremonies.",
  Nakshatra:
    "Lunar mansion — the 27 (or 28) segments of the sky the Moon traverses in ~27.3 days.",
  Yoga: "An astronomical combination of the Sun and Moon's longitudes; 27 yogas indicate the quality of activities.",
  Karana:
    "Half a tithi (~6 hours); there are 11 karanas cycling through the month.",
  Paksha:
    "Fortnight — Shukla (waxing Moon, 1st–15th) or Krishna (waning Moon, 16th–30th).",
  Rahu: "Ascending lunar node; considered malefic. Rahu Kalam = inauspicious period each day.",
  "Rahu Kalam":
    "~1.5-hour period each day ruled by Rahu (malefic node); avoid new ventures.",
  "Gulikai Kalam":
    "Period ruled by Saturn's son Gulika; inauspicious for important activities.",
  Yamaganda: "Period ruled by Yamaganda; especially inauspicious for travel.",
  "Abhijit Muhurat":
    "The most auspicious muhurat of the day, ~48 min around solar noon.",
  "Dur Muhurtam": "Inauspicious muhurat; avoid ceremonies during this period.",
  "Amrit Kalam": "Nectar period — highly auspicious for all activities.",
  Varjyam: "Moon's weakest period; avoid important activities.",
  Choghadiya:
    "Traditional Vedic time unit of ~1.5 hours; day divided into 8 slots, night into 8.",
  Hora: "Planetary hour — each day and night divided into 12 equal hours, each ruled by a planet.",
  Lagna:
    "Ascendant — the zodiac sign rising on the eastern horizon; changes every ~2 hours.",
  Muhurat:
    "Auspicious time period selected for ceremonies; 30 muhurats in a day.",
  Panchaka:
    "Five-day period with specific qualities based on Nakshatra and other factors.",
  "Jain Prahar":
    "Division of the day into 8 prahars (4 day + 4 night) with key spiritual moments.",
  "Pancha Pakshi":
    "South Indian system of five birds governing five activities across the day.",
  Samvatsara: "Hindu year name in the 60-year Jupiter cycle.",
  "Shaka Samvat":
    "Indian national calendar era, used officially; ~78 years behind Gregorian.",
  "Vikram Samvat": "Hindu luni-solar calendar; ~57 years ahead of Gregorian.",
  Amanta: "New-moon-ending lunar month system (South/West India).",
  Purnimanta: "Full-moon-ending lunar month system (North India).",
  "Sun Sign":
    "Western/Vedic zodiac position of the Sun; changes roughly monthly.",
  "Moon Sign": "Zodiac sign occupied by the Moon; changes every ~2.3 days.",
};

// ── April 2026 Festivals ───────────────────────────────────────────────────────

export const APRIL_2026_FESTIVALS: FestivalEntry[] = [
  { date: "2026-04-02", weekday: "Thursday", festivals: ["Ram Navami"] },
  {
    date: "2026-04-06",
    weekday: "Monday",
    festivals: ["Papamochani Ekadashi"],
  },
  {
    date: "2026-04-08",
    weekday: "Wednesday",
    festivals: ["Pradosh Vrat (Krishna)"],
  },
  { date: "2026-04-09", weekday: "Thursday", festivals: ["Masik Shivaratri"] },
  {
    date: "2026-04-13",
    weekday: "Monday",
    festivals: ["Chaitra Amavasya", "Baisakhi (Punjab)", "Tamil New Year"],
  },
  {
    date: "2026-04-14",
    weekday: "Tuesday",
    festivals: [
      "Ambedkar Jayanti",
      "Vishu (Kerala)",
      "Poila Boishakh (Bengal)",
    ],
  },
  { date: "2026-04-17", weekday: "Friday", festivals: ["Gangaur (Rajasthan)"] },
  { date: "2026-04-20", weekday: "Monday", festivals: ["Akshaya Tritiya"] },
  { date: "2026-04-21", weekday: "Tuesday", festivals: ["Vinayaka Chaturthi"] },
  { date: "2026-04-22", weekday: "Wednesday", festivals: ["Sheetala Saptami"] },
  { date: "2026-04-23", weekday: "Thursday", festivals: ["Rohini Vrat"] },
  {
    date: "2026-04-27",
    weekday: "Monday",
    festivals: ["Shukla Ekadashi (Mohini)"],
  },
  {
    date: "2026-04-29",
    weekday: "Wednesday",
    festivals: ["Pradosh Vrat (Shukla)"],
  },
  { date: "2026-04-30", weekday: "Thursday", festivals: ["Narasimha Jayanti"] },
];
