/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: string;
    name: string;
    createdAt: Time;
    description: string;
    stock: bigint;
    astrologicalPurpose: string;
    category: string;
    benefits: string;
    price: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    birthDate: string;
    birthTime: string;
    name: string;
    createdAt: Time;
    birthPlace: string;
    email: string;
    gotra: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface PrasadDeliveryRequest {
    id: string;
    status: string;
    userId: Principal;
    createdAt: Time;
    mobileNumber: string;
    address: string;
    templeId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderItem {
    productId: string;
    quantity: bigint;
    unitPrice: number;
}
export interface BusinessNameRecord {
    id: string;
    result: string;
    userId: Principal;
    createdAt: Time;
    businessName: string;
}
export interface BhajanEntry {
    id: string;
    title: string;
    audioBase64: string;
    createdAt: Time;
    lyricsText: string;
    artist: string;
    deity: string;
}
export interface WalletTransaction {
    id: string;
    transactionType: string;
    userId: Principal;
    createdAt: Time;
    description: string;
    amount: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AstrologerProfile {
    id: string;
    bio: string;
    name: string;
    createdAt: Time;
    languages: Array<string>;
    experienceYears: bigint;
    perMinuteRate: number;
    rating: number;
    specializations: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DevotionalContent {
    id: string;
    title: string;
    lyrics: string;
    contentType: string;
    createdAt: Time;
    language: string;
    deity: string;
}
export interface NumerologyRecord {
    id: string;
    dob: string;
    result: string;
    userId: Principal;
    name: string;
    createdAt: Time;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface VirtualTempleConfig {
    background: string;
    decorStyle: string;
    userId: Principal;
    updatedAt: Time;
    items: Array<string>;
    deity: string;
}
export interface HolyBookEntry {
    id: string;
    bookTitle: string;
    shlokaText: string;
    bookCategory: string;
    audioBase64: string;
    trackNumber: bigint;
    createdAt: Time;
    chapterTitle: string;
}
export interface ConsultationAppointment {
    id: string;
    status: string;
    topic: string;
    astrologerId: string;
    userId: Principal;
    createdAt: Time;
    preferredDateTime: string;
    notes: string;
    specialQuestions: string;
}
export interface Temple {
    id: string;
    name: string;
    createdAt: Time;
    description: string;
    deity: string;
    location: string;
}
export interface ReportRequest {
    id: string;
    dob: string;
    pob: string;
    tob: string;
    status: string;
    content: string;
    userId: Principal;
    name: string;
    createdAt: Time;
    reportType: string;
}
export interface Order {
    id: string;
    total: number;
    paymentStatus: string;
    userId: Principal;
    createdAt: Time;
    stripePaymentIntentId: string;
    items: Array<OrderItem>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ChadhavaOffering {
    id: string;
    status: string;
    userId: Principal;
    createdAt: Time;
    templeId: string;
    items: Array<string>;
}
export interface VratKathaEntry {
    id: string;
    title: string;
    audioBase64: string;
    storyText: string;
    createdAt: Time;
    festivalName: string;
}
export interface PujaBooking {
    id: string;
    status: string;
    userId: Principal;
    createdAt: Time;
    pujaType: string;
    specialWishes: string;
    gotra: string;
    preferredDate: string;
    templeId: string;
    devoteeName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    /**
     * / Admin-only: list all user profiles.
     */
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Admin-only: add a new bhajan entry.
     */
    addBhajan(entry: BhajanEntry): Promise<void>;
    /**
     * / Admin-only: add a new holy book entry.
     */
    addHolyBookEntry(entry: HolyBookEntry): Promise<void>;
    /**
     * / Authenticated users can submit a prasad delivery request for themselves.
     */
    addUserPrasadDeliveryRequest(request: PrasadDeliveryRequest): Promise<void>;
    /**
     * / Admin-only: add a new vrat katha entry.
     */
    addVratKatha(entry: VratKathaEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Admin-only: create an astrologer profile.
     */
    createAstrologerProfile(profile: AstrologerProfile): Promise<void>;
    /**
     * / Authenticated users can create a business name analysis for themselves.
     */
    createBusinessNameRecord(record: BusinessNameRecord): Promise<void>;
    /**
     * / Authenticated users can submit a chadhava offering for themselves.
     */
    createChadhavaOffering(offering: ChadhavaOffering): Promise<void>;
    /**
     * / Authenticated users can create a Stripe checkout session (e.g. for payment).
     */
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    /**
     * / Authenticated users can book a consultation appointment for themselves.
     */
    createConsultationAppointment(appointment: ConsultationAppointment): Promise<void>;
    /**
     * / Admin-only: create a devotional content entry.
     */
    createDevotionalContent(content: DevotionalContent): Promise<void>;
    /**
     * / Authenticated users can create a numerology analysis for themselves.
     */
    createNumerologyRecord(record: NumerologyRecord): Promise<void>;
    /**
     * / Authenticated users can place an order for themselves.
     */
    createOrder(order: Order): Promise<void>;
    /**
     * / Admin-only: create a product.
     */
    createProduct(product: Product): Promise<void>;
    /**
     * / Authenticated users can create a puja booking for themselves.
     */
    createPujaBooking(booking: PujaBooking): Promise<void>;
    /**
     * / Authenticated users can request a report for themselves.
     */
    createReportRequest(request: ReportRequest): Promise<void>;
    /**
     * / Admin-only: create a temple entry.
     */
    createTemple(temple: Temple): Promise<void>;
    /**
     * / Admin-only: delete a bhajan entry.
     */
    deleteBhajan(id: string): Promise<void>;
    /**
     * / Admin-only: delete a devotional content entry.
     */
    deleteDevotionalContent(id: string): Promise<void>;
    /**
     * / Admin-only: delete a holy book entry.
     */
    deleteHolyBookEntry(id: string): Promise<void>;
    /**
     * / Admin-only: delete a product.
     */
    deleteProduct(id: string): Promise<void>;
    /**
     * / Admin-only: delete a vrat katha entry.
     */
    deleteVratKatha(id: string): Promise<void>;
    /**
     * / Public: anyone may browse astrologer profiles.
     */
    getAllAstrologerProfiles(): Promise<Array<AstrologerProfile>>;
    /**
     * / Admin-only: list all appointments (for astrologer/admin dashboard).
     */
    getAllConsultationAppointments(): Promise<Array<ConsultationAppointment>>;
    /**
     * / Admin-only: get all delivery requests and puja bookings.
     */
    getAllDeliveryRequests(): Promise<[Array<[string, PrasadDeliveryRequest]>, Array<[string, PujaBooking]>]>;
    /**
     * / Public: anyone may browse devotional content.
     */
    getAllDevotionalContents(): Promise<Array<DevotionalContent>>;
    /**
     * / Public: anyone may browse products.
     */
    getAllProducts(): Promise<Array<Product>>;
    /**
     * / Public: anyone may browse temples.
     */
    getAllTemples(): Promise<Array<Temple>>;
    /**
     * / Admin-only: list all user profiles.
     */
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    /**
     * / Public: get a single astrologer profile by id.
     */
    getAstrologerProfile(id: string): Promise<AstrologerProfile | null>;
    /**
     * / Public: get a single bhajan entry by id.
     */
    getBhajanById(id: string): Promise<BhajanEntry | null>;
    /**
     * / Public: anyone may browse bhajan entries.
     */
    getBhajans(): Promise<Array<BhajanEntry>>;
    /**
     * / Get the calling user's own profile.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Public: get a single devotional content entry.
     */
    getDevotionalContent(id: string): Promise<DevotionalContent | null>;
    /**
     * / Public: anyone may browse holy book entries, optionally filtered by bookTitle.
     */
    getHolyBookEntries(bookTitle: string): Promise<Array<HolyBookEntry>>;
    /**
     * / Public: get a single holy book entry by id.
     */
    getHolyBookEntryById(id: string): Promise<HolyBookEntry | null>;
    /**
     * / Admin-only: list all pending prasad deliveries.
     */
    getPendingPrasadDeliveries(): Promise<Array<PrasadDeliveryRequest>>;
    /**
     * / Public: get a single product.
     */
    getProduct(id: string): Promise<Product | null>;
    /**
     * / Authenticated users can check a Stripe session status (e.g. after checkout).
     */
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    /**
     * / Users may only fetch their own business name records; admins may fetch any.
     */
    getUserBusinessNameRecords(userId: Principal): Promise<Array<BusinessNameRecord>>;
    /**
     * / Users may only fetch their own offerings; admins may fetch any user's offerings.
     */
    getUserChadhavaOfferings(userId: Principal): Promise<Array<ChadhavaOffering>>;
    /**
     * / Users may only fetch their own appointments; admins may fetch any user's.
     */
    getUserConsultationAppointments(userId: Principal): Promise<Array<ConsultationAppointment>>;
    /**
     * / Users may only fetch their own numerology records; admins may fetch any.
     */
    getUserNumerologyRecords(userId: Principal): Promise<Array<NumerologyRecord>>;
    /**
     * / Users may only fetch their own orders; admins may fetch any user's.
     */
    getUserOrders(userId: Principal): Promise<Array<Order>>;
    /**
     * / Users may only fetch their own delivery requests; admins may fetch any.
     */
    getUserPrasadDeliveryRequests(userId: Principal): Promise<Array<PrasadDeliveryRequest>>;
    /**
     * / Fetch another user's profile. Users may only fetch their own; admins may fetch any.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Users may only fetch their own bookings; admins may fetch any user's bookings.
     */
    getUserPujaBookings(userId: Principal): Promise<Array<PujaBooking>>;
    /**
     * / Users may only fetch their own report requests; admins may fetch any user's.
     */
    getUserReportRequests(userId: Principal): Promise<Array<ReportRequest>>;
    /**
     * / Users may only fetch their own temple config; admins may fetch any.
     */
    getVirtualTempleConfig(userId: Principal): Promise<VirtualTempleConfig | null>;
    /**
     * / Public: get a single vrat katha entry by id.
     */
    getVratKathaById(id: string): Promise<VratKathaEntry | null>;
    /**
     * / Public: anyone may browse vrat katha entries.
     */
    getVratKathas(): Promise<Array<VratKathaEntry>>;
    /**
     * / Authenticated users can get their own wallet balance; admins can get any.
     */
    getWalletBalance(userId: Principal): Promise<number>;
    /**
     * / Authenticated users can get their own transaction history; admins can get any.
     */
    getWalletTransactions(userId: Principal): Promise<Array<WalletTransaction>>;
    /**
     * / Admin-only: update the status of a puja booking.
     */
    handlePujaBooking(bookingId: string, status: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Public: check whether Stripe has been configured.
     */
    isStripeConfigured(): Promise<boolean>;
    /**
     * / Authenticated users can add funds to their own wallet (recharge).
     */
    rechargeWallet(userId: Principal, amount: number, transaction: WalletTransaction): Promise<void>;
    /**
     * / Save / update the calling user's own profile.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Authenticated users can save their own virtual temple configuration.
     */
    saveVirtualTempleConfig(config: VirtualTempleConfig): Promise<void>;
    /**
     * / Admin-only: set the Stripe configuration.
     */
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    /**
     * / Admin-only: update an existing bhajan entry.
     */
    updateBhajan(entry: BhajanEntry): Promise<void>;
    /**
     * / Admin-only: update appointment status and notes.
     */
    updateConsultationAppointment(id: string, status: string, notes: string): Promise<void>;
    /**
     * / Admin-only: update an existing devotional content entry.
     */
    updateDevotionalContent(content: DevotionalContent): Promise<void>;
    /**
     * / Admin-only: update an existing holy book entry.
     */
    updateHolyBookEntry(entry: HolyBookEntry): Promise<void>;
    /**
     * / Admin-only: update order payment status.
     */
    updateOrderPaymentStatus(id: string, paymentStatus: string, stripePaymentIntentId: string): Promise<void>;
    /**
     * / Admin-only: update the status of a prasad delivery request.
     */
    updatePrasadDeliveryStatus(id: string, status: string): Promise<void>;
    /**
     * / Admin-only: update a product.
     */
    updateProduct(product: Product): Promise<void>;
    /**
     * / Admin-only: update report status and content.
     */
    updateReportRequest(id: string, status: string, content: string): Promise<void>;
    /**
     * / Admin-only: update an existing vrat katha entry.
     */
    updateVratKatha(entry: VratKathaEntry): Promise<void>;
}
import type { AstrologerProfile as _AstrologerProfile, BhajanEntry as _BhajanEntry, DevotionalContent as _DevotionalContent, HolyBookEntry as _HolyBookEntry, Product as _Product, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, VirtualTempleConfig as _VirtualTempleConfig, VratKathaEntry as _VratKathaEntry, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBhajan(arg0: BhajanEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBhajan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBhajan(arg0);
            return result;
        }
    }
    async addHolyBookEntry(arg0: HolyBookEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHolyBookEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHolyBookEntry(arg0);
            return result;
        }
    }
    async addUserPrasadDeliveryRequest(arg0: PrasadDeliveryRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserPrasadDeliveryRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserPrasadDeliveryRequest(arg0);
            return result;
        }
    }
    async addVratKatha(arg0: VratKathaEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVratKatha(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVratKatha(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAstrologerProfile(arg0: AstrologerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAstrologerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAstrologerProfile(arg0);
            return result;
        }
    }
    async createBusinessNameRecord(arg0: BusinessNameRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusinessNameRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusinessNameRecord(arg0);
            return result;
        }
    }
    async createChadhavaOffering(arg0: ChadhavaOffering): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChadhavaOffering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChadhavaOffering(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createConsultationAppointment(arg0: ConsultationAppointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createConsultationAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConsultationAppointment(arg0);
            return result;
        }
    }
    async createDevotionalContent(arg0: DevotionalContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDevotionalContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDevotionalContent(arg0);
            return result;
        }
    }
    async createNumerologyRecord(arg0: NumerologyRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNumerologyRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNumerologyRecord(arg0);
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async createPujaBooking(arg0: PujaBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPujaBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPujaBooking(arg0);
            return result;
        }
    }
    async createReportRequest(arg0: ReportRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReportRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReportRequest(arg0);
            return result;
        }
    }
    async createTemple(arg0: Temple): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemple(arg0);
            return result;
        }
    }
    async deleteBhajan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBhajan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBhajan(arg0);
            return result;
        }
    }
    async deleteDevotionalContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDevotionalContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDevotionalContent(arg0);
            return result;
        }
    }
    async deleteHolyBookEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHolyBookEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHolyBookEntry(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteVratKatha(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVratKatha(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVratKatha(arg0);
            return result;
        }
    }
    async getAllAstrologerProfiles(): Promise<Array<AstrologerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAstrologerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAstrologerProfiles();
            return result;
        }
    }
    async getAllConsultationAppointments(): Promise<Array<ConsultationAppointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConsultationAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConsultationAppointments();
            return result;
        }
    }
    async getAllDeliveryRequests(): Promise<[Array<[string, PrasadDeliveryRequest]>, Array<[string, PujaBooking]>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryRequests();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryRequests();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getAllDevotionalContents(): Promise<Array<DevotionalContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevotionalContents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevotionalContents();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllTemples(): Promise<Array<Temple>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTemples();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTemples();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getAstrologerProfile(arg0: string): Promise<AstrologerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAstrologerProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAstrologerProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBhajanById(arg0: string): Promise<BhajanEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBhajanById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBhajanById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBhajans(): Promise<Array<BhajanEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBhajans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBhajans();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevotionalContent(arg0: string): Promise<DevotionalContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevotionalContent(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevotionalContent(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHolyBookEntries(arg0: string): Promise<Array<HolyBookEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolyBookEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolyBookEntries(arg0);
            return result;
        }
    }
    async getHolyBookEntryById(arg0: string): Promise<HolyBookEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolyBookEntryById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolyBookEntryById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPrasadDeliveries(): Promise<Array<PrasadDeliveryRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPrasadDeliveries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPrasadDeliveries();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBusinessNameRecords(arg0: Principal): Promise<Array<BusinessNameRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBusinessNameRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBusinessNameRecords(arg0);
            return result;
        }
    }
    async getUserChadhavaOfferings(arg0: Principal): Promise<Array<ChadhavaOffering>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserChadhavaOfferings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserChadhavaOfferings(arg0);
            return result;
        }
    }
    async getUserConsultationAppointments(arg0: Principal): Promise<Array<ConsultationAppointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserConsultationAppointments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserConsultationAppointments(arg0);
            return result;
        }
    }
    async getUserNumerologyRecords(arg0: Principal): Promise<Array<NumerologyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNumerologyRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNumerologyRecords(arg0);
            return result;
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return result;
        }
    }
    async getUserPrasadDeliveryRequests(arg0: Principal): Promise<Array<PrasadDeliveryRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPrasadDeliveryRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPrasadDeliveryRequests(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPujaBookings(arg0: Principal): Promise<Array<PujaBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPujaBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPujaBookings(arg0);
            return result;
        }
    }
    async getUserReportRequests(arg0: Principal): Promise<Array<ReportRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserReportRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserReportRequests(arg0);
            return result;
        }
    }
    async getVirtualTempleConfig(arg0: Principal): Promise<VirtualTempleConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVirtualTempleConfig(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVirtualTempleConfig(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVratKathaById(arg0: string): Promise<VratKathaEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVratKathaById(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVratKathaById(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVratKathas(): Promise<Array<VratKathaEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVratKathas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVratKathas();
            return result;
        }
    }
    async getWalletBalance(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance(arg0);
            return result;
        }
    }
    async getWalletTransactions(arg0: Principal): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletTransactions(arg0);
            return result;
        }
    }
    async handlePujaBooking(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handlePujaBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handlePujaBooking(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async rechargeWallet(arg0: Principal, arg1: number, arg2: WalletTransaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rechargeWallet(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rechargeWallet(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveVirtualTempleConfig(arg0: VirtualTempleConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVirtualTempleConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVirtualTempleConfig(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBhajan(arg0: BhajanEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBhajan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBhajan(arg0);
            return result;
        }
    }
    async updateConsultationAppointment(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConsultationAppointment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConsultationAppointment(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDevotionalContent(arg0: DevotionalContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDevotionalContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDevotionalContent(arg0);
            return result;
        }
    }
    async updateHolyBookEntry(arg0: HolyBookEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHolyBookEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHolyBookEntry(arg0);
            return result;
        }
    }
    async updateOrderPaymentStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderPaymentStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderPaymentStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePrasadDeliveryStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrasadDeliveryStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrasadDeliveryStatus(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updateReportRequest(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async updateVratKatha(arg0: VratKathaEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVratKatha(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVratKatha(arg0);
            return result;
        }
    }
}
function from_candid_StripeSessionStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AstrologerProfile]): AstrologerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BhajanEntry]): BhajanEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DevotionalContent]): DevotionalContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HolyBookEntry]): HolyBookEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VirtualTempleConfig]): VirtualTempleConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VratKathaEntry]): VratKathaEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n20(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
